### ISSUE TITLE
Enhance charm to optionally generate subject alternative names (SAN)

### ISSUE THREAD

**Issue by coccolesto** [canonical/tls-certificates-requirer-operator#118]
### Enhancement Proposal

It could be very useful to optionally configure a SAN parameter.
When submitting a cert request many applications that use HA (es hacluster) use SAN  for storing vip, endpoint ips, local names. 
In this way the cert can be shared to all the endpoint forming a cluster.

**Comment by gruyaume** [comment]
Hello @coccolesto , PR #121  will address this request. Feel free to review it to ensure it matches with your expectations.
