### ISSUE TITLE
 tls-certificate-requirer charm stuck at waiting status after relation joined

### ISSUE THREAD

**Issue by gatici** [canonical/tls-certificates-requirer-operator#17]
Integration test in this PR https://github.com/canonical/tls-certificates-requirer-operator/pull/14/files/8a537bdcef96dcf7e1aa782986d757108b48c0b5#  fails .

Assumption 1:   tls-certificate-requirer charm expect to get CertificateAvailable event,  then it can become Active.  However,  self-signed-certificates charm does not emit this event. This needs to be implemented in the provider charm.

Assumption 2:  the change which is done in config_changed method could be the reason of problem. We are not sure how OpsTest handles the event.defers(). Is it running config_changed again and requesting certificate or not requesting ?

**Comment by patriciareinoso** [comment]
Juju 3.1.6 fixes the problem. 
juju 3.1.6 is on edge. Need to wait for it to be stable.

**Comment by saltiyazan** [comment]
is this issue fixed now? @patriciareinoso @gatici

**Comment by gatici** [comment]
> is this issue fixed now? @patriciareinoso @gatici

Yes, it's fixed with that PR: https://github.com/canonical/tls-certificates-requirer-operator/pull/14.
